// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://spade.storage",
        "contact": {
            "name": "API Support",
            "url": "https://docs.spade.storage"
        },
        "license": {
            "name": "Apache 2.0 Apache-2.0 OR MIT",
            "url": "https://github.com/data-preservation-programs/spade/blob/master/LICENSE.md"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/address": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get addresses used by a tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.ResponseEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "response": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.Address"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "produces": [
                    "application/json"
                ],
                "summary": "Update addresses associated with a tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "New addresses to add or change is_signing flag of",
                        "name": "addresses",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.Address"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.ResponseEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "response": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.Address"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "summary": "Delete addresses used by a tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "addresses to delete",
                        "name": "addresses",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.ResponseEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "response": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.Address"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/collections": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Gets info about collections",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.ResponseEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "response": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.Collection"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Creates a new collection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "Collection to create",
                        "name": "collection",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateCollectionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.ResponseEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "response": {
                                            "$ref": "#/definitions/api.CreateCollectionResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/constraint-labels": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "List all constraint labels for the tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.ResponseEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "response": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.Label"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/eligibility-criteria": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get sp eligibility criteria",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.ResponseEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "response": {
                                            "$ref": "#/definitions/api.EligibilityCriteria"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Set sp eligibility criteria",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "New eligibility criteria to update to",
                        "name": "elibility_criteria",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.EligibilityCriteria"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.ResponseEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "response": {
                                            "$ref": "#/definitions/api.EligibilityCriteria"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/settings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get the currently active Tenant Settings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.ResponseEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "response": {
                                            "$ref": "#/definitions/api.Settings"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Apply new Tenant Settings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "New settings to apply",
                        "name": "settings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.Settings"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.ResponseEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "response": {
                                            "$ref": "#/definitions/api.Settings"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "This endpoint is used to check the health of the service",
                "produces": [
                    "application/json"
                ],
                "summary": "Simple health check endpoint",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.ResponseEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "response": {
                                            "$ref": "#/definitions/api.StatusResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/storage-contract": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get tenant storage contract",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.ResponseEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "response": {
                                            "$ref": "#/definitions/api.GetStorageContractResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "Updates the storage contract *note* this will require SPs to resubscribe if changed",
                "produces": [
                    "application/json"
                ],
                "summary": "Update storage contract",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "New Storage Contract to update to",
                        "name": "collection",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.StorageContract"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.ResponseEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "response": {
                                            "$ref": "#/definitions/api.StorageContract"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/storage-providers": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get list of Storage Providers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.ResponseEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "response": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.StorageProvider"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/storage-providers/approve": {
            "post": {
                "description": "Note: This is only required if auto_approve is false, requiring manual approval of SP subscription",
                "produces": [
                    "application/json"
                ],
                "summary": "Approves a list of Storage Providers to work with the tenant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "List of SP IDs to approve",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.StorageProviderIDs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.ResponseEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "response": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.StorageProvider"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/storage-providers/suspend": {
            "post": {
                "description": "Note: This is only required if auto_suspend is false, as manual suspension is required",
                "produces": [
                    "application/json"
                ],
                "summary": "Suspend storage providers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Auth token",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "List of SP IDs to suspend",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.StorageProviderIDs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/api.ResponseEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "response": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/api.StorageProvider"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Address": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "is_signing": {
                    "description": "true - active dealmaking from this address, false - still counts as an associated wallet",
                    "type": "boolean"
                }
            }
        },
        "api.Collection": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "todo: UUIDs",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "replication_constraints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ReplicationConstraint"
                    }
                }
            }
        },
        "api.CreateCollectionRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "piece_source": {
                    "$ref": "#/definitions/api.PieceSource"
                },
                "replication_constraints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ReplicationConstraint"
                    }
                }
            }
        },
        "api.CreateCollectionResponse": {
            "type": "object",
            "properties": {
                "collection_id": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api.EligibilityClause": {
            "type": "object",
            "properties": {
                "attribute": {
                    "type": "string"
                },
                "operator": {
                    "type": "string"
                },
                "value": {
                    "description": "TODO: type - either []string or string"
                }
            }
        },
        "api.EligibilityCriteria": {
            "type": "object",
            "properties": {
                "clauses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.EligibilityClause"
                    }
                }
            }
        },
        "api.GetStorageContractResponse": {
            "type": "object",
            "properties": {
                "cid": {
                    "type": "string"
                },
                "content": {
                    "type": "object",
                    "properties": {
                        "info_lines": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                },
                "retrieval": {
                    "type": "object",
                    "properties": {
                        "mechanisms": {
                            "type": "object",
                            "properties": {
                                "ipld_bitswap": {
                                    "type": "boolean"
                                },
                                "piece_rrhttp": {
                                    "type": "boolean"
                                }
                            }
                        },
                        "sla": {
                            "type": "object",
                            "properties": {
                                "info_lines": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "api.Label": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                }
            }
        },
        "api.PieceSource": {
            "type": "object",
            "properties": {
                "method": {
                    "type": "string"
                }
            }
        },
        "api.ReplicationConstraint": {
            "type": "object",
            "properties": {
                "constraint_id": {
                    "type": "integer"
                },
                "constraint_max": {
                    "type": "integer"
                }
            }
        },
        "api.ResponseEnvelope": {
            "type": "object",
            "properties": {
                "error_code": {
                    "type": "integer"
                },
                "error_lines": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "error_slug": {
                    "type": "string"
                },
                "info_lines": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "request_id": {
                    "type": "string"
                },
                "response": {},
                "response_code": {
                    "type": "integer"
                },
                "response_entries": {
                    "type": "integer"
                },
                "response_state_epoch": {
                    "type": "integer"
                },
                "response_timestamp": {
                    "type": "string"
                }
            }
        },
        "api.Settings": {
            "type": "object",
            "properties": {
                "auto_approve": {
                    "type": "boolean"
                },
                "auto_suspend": {
                    "type": "boolean"
                }
            }
        },
        "api.StatusResponse": {
            "type": "object",
            "properties": {
                "alive": {
                    "type": "boolean"
                }
            }
        },
        "api.StorageContract": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "object",
                    "properties": {
                        "info_lines": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                },
                "retrieval": {
                    "type": "object",
                    "properties": {
                        "mechanisms": {
                            "type": "object",
                            "properties": {
                                "ipld_bitswap": {
                                    "type": "boolean"
                                },
                                "piece_rrhttp": {
                                    "type": "boolean"
                                }
                            }
                        },
                        "sla": {
                            "type": "object",
                            "properties": {
                                "info_lines": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "api.StorageProvider": {
            "type": "object",
            "properties": {
                "sp_id": {
                    "type": "string"
                },
                "status": {
                    "description": "* ENUM: [ eligible, pending-approval, active, suspended ]",
                    "type": "string"
                },
                "subscription_date": {
                    "type": "string"
                }
            }
        },
        "api.StorageProviderIDs": {
            "type": "object",
            "properties": {
                "sp_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "api.spade.storage",
	BasePath:         "/tenant",
	Schemes:          []string{},
	Title:            "Spade Tenant API",
	Description:      "This is the API for the Spade Tenant Application",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
