info:
  contact: {}
paths:
  /handleHealth:
    get:
      description: This endpoint is used to check the health of the service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema: {}
      summary: Simple health check endpoint
swagger: "2.0"
